### ISSUE TITLE
Import to export produces code not compatible with IE8.

### ISSUE THREAD

**Issue by Serabe** [esperantojs/esperanto#94] opened 2015-02-02 11:35 UTC
The following code:

```js
import later from 'later';

export {later};
```

transpiles to:

```js
define(['exports', 'later'], function (exports, later) {

	'use strict';

	Object.defineProperty(exports, 'later', { get: function () { return later['default']; }});

	// example from http://jsmodules.io

});
```

That does not work in IE8 since exports is not a DOM node.

On the other hand, this code:

```js
// example from http://jsmodules.io
import l from 'later';

var later = l;

export {later};
```

transpiles to

```js
define(['exports', 'later'], function (exports, l) {

	'use strict';

	// example from http://jsmodules.io
	var later = l['default'];

	exports.later = later;

});
```

That is IE8 compatible. This could serve as a workaround until it gets fixed.

**Comment by rwjblue** [comment] 2015-02-02 12:36
This is not an issue with 0.6.7. https://github.com/esperantojs/esperanto/pull/89 Addressed this exact concern.

**Comment by rwjblue** [comment] 2015-02-02 13:00
I spoke with @serabe in IRC, and the issue is regarding an ember-cli app (which doesn't yet expose the new flag).  I should have that updated today, and we will likely release a new version of ember-cli to restore IE8 compatibility.

**Comment by Rich-Harris** [comment] 2015-02-02 13:13
Great, thanks - will close this issue

**Closed by Rich-Harris** 2015-02-02 13:13 UTC

**Comment by rwjblue** [comment] 2015-02-02 21:27
https://github.com/ember-cli/ember-cli/pull/3183 should fix this up (in case any other intrepid travelers come across this thread).
