### ISSUE TITLE
use strict output twice

### ISSUE THREAD

**Issue by thejameskyle** [esperantojs/esperanto#121] opened 2015-03-11 06:01 UTC
Input:
```js
'use strict';
```

Output:
```js
'use strict';

'use strict';
```

:cry:

**Comment by stefanpenner** [comment] 2015-03-11 17:54
@thejameskyle I don't see this in my usages of esperanto, do you have steps to reproduce?

**Comment by thejameskyle** [comment] 2015-03-11 18:56
I just tested it out on http://esperantojs.org/

**Comment by Rich-Harris** [comment] 2015-03-11 19:08
Yeah, at the moment it doesn't bother checking, the assumption being that if you're writing ES6 modules you're not explicitly using the 'use strict' pragma because you don't have a choice. A good minifier should eliminate the second one, though I don't know off the top of my head if that happens in practice.

My typical workflow involves transpiling with babel then bundling with esperanto. In that case I just blacklist (or don't whitelist) the `useStrict` transform. Though I guess we could detect whether there's already a redundant 'use strict' and skip it if so.

**Comment by stefanpenner** [comment] 2015-03-15 22:38
i don't see this as a bug

**Comment by eventualbuddha** [comment] 2015-03-30 22:19
I'm inclined to agree that there's little benefit in checking for this. Closing.

**Closed by eventualbuddha** 2015-03-30 22:19 UTC

**Comment by Rich-Harris** [comment] 2015-04-07 15:11
This turned out to be necessary for #141, so you can now pass a `useStrict: false` option and it'll be omitted.
